export interface Colors {
    "primary": string;
    "onPrimary": string;
    "primaryContainer": string;
    "onPrimaryContainer": string;
    "primaryFixed": string;
    "onPrimaryFixed": string;
    "primaryFixedDim": string;
    "onPrimaryFixedVariant": string;
    "inversePrimary": string;
    // secondary
    "secondary": string;
    "onSecondary": string;
    "secondaryContainer": string;
    "onSecondaryContainer": string;
    "secondaryFixed": string;
    "onSecondaryFixed": string;
    "secondaryFixedDim": string;
    "onSecondaryFixedVariant": string;
    // tertiary
    "tertiary": string;
    "onTertiary": string;
    "tertiaryContainer": string;
    "onTertiaryContainer": string;
    "tertiaryFixed": string;
    "onTertiaryFixed": string;
    "tertiaryFixedDim": string;
    "onTertiaryFixedVariant": string;
    // error
    "error": string;
    "onError": string;
    "errorContainer": string;
    "onErrorContainer": string;
    // surface
    "surface": string;
    "onSurface": string;
    "surfaceVariant": string;
    "onSurfaceVariant": string;
    "surfaceDim": string;
    "surfaceBright": string;
    "surfaceContainerLowest": string;
    "surfaceContainerLow": string;
    "surfaceContainer": string;
    "surfaceContainerHigh": string;
    "surfaceContainerHighest": string;
    "inverseSurface": string;
    "inverseOnSurface": string;
    // background
    "background": string;
    "onBackground": string;
    "outline": string;
    "outlineVariant": string;
    "shadow": string;
    "scrim": string;
    "black": string;
    "white": string;
}

export interface BgColors {
    "bg-primary": string;
    "bg-onPrimary": string;
    "bg-primaryContainer": string;
    "bg-onPrimaryContainer": string;
    "bg-primaryFixed": string;
    "bg-onPrimaryFixed": string;
    "bg-primaryFixedDim": string;
    "bg-onPrimaryFixedVariant": string;
    "bg-inversePrimary": string;
    // secondary
    "bg-secondary": string;
    "bg-onSecondary": string;
    "bg-secondaryContainer": string;
    "bg-onSecondaryContainer": string;
    "bg-secondaryFixed": string;
    "bg-onSecondaryFixed": string;
    "bg-secondaryFixedDim": string;
    "bg-onSecondaryFixedVariant": string;
    // tertiary
    "bg-tertiary": string;
    "bg-onTertiary": string;
    "bg-tertiaryContainer": string;
    "bg-onTertiaryContainer": string;
    "bg-tertiaryFixed": string;
    "bg-onTertiaryFixed": string;
    "bg-tertiaryFixedDim": string;
    "bg-onTertiaryFixedVariant": string;
    // error
    "bg-error": string;
    "bg-onError": string;
    "bg-errorContainer": string;
    "bg-onErrorContainer": string;
    // surface
    "bg-surface": string;
    "bg-onSurface": string;
    "bg-surfaceVariant": string;
    "bg-onSurfaceVariant": string;
    "bg-surfaceDim": string;
    "bg-surfaceBright": string;
    "bg-surfaceContainerLowest": string;
    "bg-surfaceContainerLow": string;
    "bg-surfaceContainer": string;
    "bg-surfaceContainerHigh": string;
    "bg-surfaceContainerHighest": string;
    "bg-inverseSurface": string;
    "bg-inverseOnSurface": string;
    // background
    "bg-background": string;
    "bg-onBackground": string;
    "bg-outline": string;
    "bg-outlineVariant": string;
    "bg-shadow": string;
    "bg-scrim": string;
    "bg-black": string;
    "bg-white": string;
}

export interface TextColors {
    "text-primary": string;
    "text-onPrimary": string;
    "text-primaryContainer": string;
    "text-onPrimaryContainer": string;
    "text-primaryFixed": string;
    "text-onPrimaryFixed": string;
    "text-primaryFixedDim": string;
    "text-onPrimaryFixedVariant": string;
    "text-inversePrimary": string;
    // secondary
    "text-secondary": string;
    "text-onSecondary": string;
    "text-secondaryContainer": string;
    "text-onSecondaryContainer": string;
    "text-secondaryFixed": string;
    "text-onSecondaryFixed": string;
    "text-secondaryFixedDim": string;
    "text-onSecondaryFixedVariant": string;
    // tertiary
    "text-tertiary": string;
    "text-onTertiary": string;
    "text-tertiaryContainer": string;
    "text-onTertiaryContainer": string;
    "text-tertiaryFixed": string;
    "text-onTertiaryFixed": string;
    "text-tertiaryFixedDim": string;
    "text-onTertiaryFixedVariant": string;
    // error
    "text-error": string;
    "text-onError": string;
    "text-errorContainer": string;
    "text-onErrorContainer": string;
    // surface
    "text-surface": string;
    "text-onSurface": string;
    "text-surfaceVariant": string;
    "text-onSurfaceVariant": string;
    "text-surfaceDim": string;
    "text-surfaceBright": string;
    "text-surfaceContainerLowest": string;
    "text-surfaceContainerLow": string;
    "text-surfaceContainer": string;
    "text-surfaceContainerHigh": string;
    "text-surfaceContainerHighest": string;
    "text-inverseSurface": string;
    "text-inverseOnSurface": string;
    // background
    "text-background": string;
    "text-onBackground": string;
    "text-outline": string;
    "text-outlineVariant": string;
    "text-shadow": string;
    "text-scrim": string;
    "text-black": string;
    "text-white": string;
}
